#
# CommandFixer [VERSION 1.0]
#
# Permissions:
# - cmd.override = Override the fixed command
#
# The general options
#
General:
  #
  # The list of all the commands to fix. Put them into their lower-chars version
  # Values: A list of Strings (to lower characters)
  #
  Commands:
    - //calc
    - //calculate
    - //solve
    - //eval
    - //evaluate
    - /minecraft:me
    - /me
  #
  # The message that will be sent to the player when he try to execute a fixed command
  # Value: String
  #
  FixedCommandMessage: "&4[CommandFixer]&c You can't use this command!"